import type { ForensicAuditReport } from "./audit-schema";

import blockedShot from "@/assets/audit-blocked.jpg";
import atelierCartShot from "@/assets/audit-loomandlark.jpg";
import atelierMiniCartShot from "@/assets/audit-atelier-minicart.jpg";
import atelierProductShot from "@/assets/audit-atelier-product.jpg";
import techCartShot from "@/assets/audit-voltique.jpg";
import techCategoryShot from "@/assets/audit-techbazaar-category.jpg";
import techProductShot from "@/assets/audit-techbazaar-product.jpg";
import wayfarerCartShot from "@/assets/audit-summitgear.jpg";
import wayfarerProductShot from "@/assets/audit-wayfarer-product.jpg";

/**
 * Fixture reports. These double as the demo corpus: a live run can be blocked
 * or slow, and the product should always have something real to show.
 *
 * Every report is a journey — one stage per page the agent actually landed on.
 */

const wayfarer: ForensicAuditReport = {
  id: "wayfarer-outdoor",
  url: "https://wayfarer-outdoor.com/p/atmos-ag-65-backpack",
  domain: "wayfarer-outdoor.com",
  status: "complete",
  blocked_reason: null,
  captured_at: "2026-08-08T09:14:22.000Z",
  run_duration_ms: 41280,
  steps: [
    { actor: "system", text: "Initializing forensic run 8f2c · budget 60s", delay_ms: 0, tone: "normal" },
    { actor: "browser", text: "Session acquired · chromium 128 · viewport 1280x1920", delay_ms: 700, tone: "normal" },
    { actor: "browser", text: "GET /p/atmos-ag-65-backpack → 200 in 1842ms", delay_ms: 900, tone: "normal" },
    { actor: "browser", text: "Waiting for network idle… settled after 3 pending requests", delay_ms: 800, tone: "normal" },
    { actor: "browser", text: "Accessibility tree extracted · 214 nodes · 9 button candidates", delay_ms: 750, tone: "normal" },
    { actor: "vision", text: "Auditing product page: buy affordance, variants, quantity…", delay_ms: 900, tone: "normal" },
    { actor: "vision", text: "5 friction points localised on product page", delay_ms: 850, tone: "warn" },
    { actor: "vision", text: 'Selected [data-testid="add-to-cart"] · confidence 0.94', delay_ms: 800, tone: "success" },
    { actor: "browser", text: "click() dispatched · navigation to /cart in 1104ms", delay_ms: 900, tone: "normal" },
    { actor: "browser", text: "Stage 2 reached: Cart · no interstitial", delay_ms: 700, tone: "success" },
    { actor: "browser", text: "Console: 2 errors captured during cart render", delay_ms: 650, tone: "warn" },
    { actor: "browser", text: "Performance entries collected · LCP 2418ms · CLS 0.061", delay_ms: 700, tone: "normal" },
    { actor: "vision", text: "Running CRO + WCAG pass over cart capture…", delay_ms: 1000, tone: "normal" },
    { actor: "vision", text: "4 friction points localised to DOM bounding boxes", delay_ms: 900, tone: "success" },
    { actor: "system", text: "Report sealed · 2 stages · run complete", delay_ms: 600, tone: "success" },
  ],
  stages: [
    {
      id: "product",
      kind: "product",
      label: "Product page",
      url: "https://wayfarer-outdoor.com/p/atmos-ag-65-backpack",
      transition_in: null,
      screenshot: {
        src: wayfarerProductShot,
        width: 1024,
        height: 1536,
        caption: "Product page as served, full-page capture at 1280 x 1920",
      },
      technical_metrics: {
        largest_contentful_paint_ms: 2180,
        cumulative_layout_shift: 0.042,
        total_blocking_time_ms: 240,
        dom_content_loaded_ms: 1842,
        transfer_bytes: 4_112_384,
        request_count: 64,
        console_errors: ['Refused to load script "https://cdn.trkpx.io/tag.js" — blocked by client'],
        slow_resources: [
          { label: "pack-hero-4k.jpg (1.4 MB)", duration_ms: 1610 },
          { label: "reviews-widget.bundle.js", duration_ms: 820 },
        ],
      },
      friction_points: [
        {
          id: 1,
          x_percentage: 76,
          y_percentage: 54.1,
          severity: "high",
          category: "clarity",
          title: "Two buy buttons compete at the decision point",
          description:
            "Add to Cart and a full-width violet Buy with Shop Pay sit stacked with equal weight. The express button is visually louder than the primary action, splitting intent at the single moment the page exists to serve.",
          evidence: "Both full-width · express CTA higher contrast than primary",
          selector: ".product-form__buttons",
        },
        {
          id: 2,
          x_percentage: 76,
          y_percentage: 38.4,
          severity: "medium",
          category: "form",
          title: "Size is pre-selected without the user choosing",
          description:
            "The torso-length select defaults to Medium with no empty state. A buyer who never reads the control ships the wrong size, and returns on a $319 pack are the most expensive kind.",
          evidence: 'select[name="torso"] defaults to "Medium (18\u2033 – 20\u2033)" · no placeholder option',
          selector: "select[name='torso']",
        },
        {
          id: 3,
          x_percentage: 63,
          y_percentage: 44.7,
          severity: "low",
          category: "accessibility",
          title: "Quantity stepper targets are 28 px",
          description:
            "The minus and plus controls are 28 x 28 px, below the 44 px touch-target guidance, and the number between them is not an editable input — buying five means five taps.",
          evidence: "Stepper buttons 28x28 px · value node is a <span>",
          selector: ".quantity__stepper",
        },
        {
          id: 4,
          x_percentage: 73,
          y_percentage: 63,
          severity: "medium",
          category: "clarity",
          title: "Free-shipping threshold sits below the buy button",
          description:
            "Free shipping over $75 renders under both CTAs in muted grey. The one incentive that raises basket size is placed where the user has already decided.",
          evidence: "Shipping note 180 px below primary CTA · #767676 on #FFFFFF",
          selector: ".shipping-note",
        },
        {
          id: 5,
          x_percentage: 18,
          y_percentage: 95.6,
          severity: "low",
          category: "clarity",
          title: "Bundle row repeats Add to Cart three more times",
          description:
            "Complete your kit adds three identical Add to Cart buttons below the fold. Accessibility-tree candidates for the real buy action jump from one to four, and so does the user's ambiguity.",
          evidence: "4 nodes matching /add to cart/i on the page",
          selector: ".complete-kit .product-card__cta",
        },
      ],
    },
    {
      id: "cart",
      kind: "cart",
      label: "Cart",
      url: "https://wayfarer-outdoor.com/cart",
      transition_in: { action: 'click [data-testid="add-to-cart"] → navigate /cart', duration_ms: 1104 },
      screenshot: {
        src: wayfarerCartShot,
        width: 1024,
        height: 1536,
        caption: "Cart page after Add to Cart, full-page capture at 1280 x 1920",
      },
      technical_metrics: {
        largest_contentful_paint_ms: 2418,
        cumulative_layout_shift: 0.061,
        total_blocking_time_ms: 310,
        dom_content_loaded_ms: 1104,
        transfer_bytes: 3_284_992,
        request_count: 87,
        console_errors: [
          'Refused to load script "https://cdn.trkpx.io/tag.js" — blocked by client',
          "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'dataset')",
        ],
        slow_resources: [
          { label: "hero-tent-4k.jpg (1.1 MB)", duration_ms: 1420 },
          { label: "reviews-widget.bundle.js", duration_ms: 890 },
          { label: "afterpay-messaging.js", duration_ms: 640 },
        ],
      },
      friction_points: [
        {
          id: 1,
          x_percentage: 83,
          y_percentage: 32.5,
          severity: "medium",
          category: "clarity",
          title: "Tax is estimated but never explained",
          description:
            "The summary shows Estimated Tax $23.20 with no jurisdiction or recalculation note. Estimate language this close to the total is a known abandonment trigger for first-time buyers.",
          evidence: "Order summary row 3 · no tooltip, no link",
          selector: ".order-summary__tax",
        },
        {
          id: 2,
          x_percentage: 83,
          y_percentage: 38.4,
          severity: "low",
          category: "trust",
          title: "Two competing primary actions",
          description:
            "Proceed to Checkout and Check out with PayPal are stacked with equal visual weight, splitting attention at the single highest-intent moment on the page.",
          evidence: "Both buttons full-width, adjacent, separated only by an OR rule",
          selector: ".order-summary__actions",
        },
        {
          id: 3,
          x_percentage: 50,
          y_percentage: 66,
          severity: "medium",
          category: "clarity",
          title: "Trust badge row pushes checkout out of view",
          description:
            "Four review badges and a guarantee strip occupy 380 px directly under the fold, so a returning buyer scrolling to confirm shipping loses sight of the checkout button entirely.",
          evidence: "Badge strip height 380 px · checkout CTA scrolled out at 900 px",
          selector: ".trust-strip",
        },
        {
          id: 4,
          x_percentage: 49,
          y_percentage: 80.5,
          severity: "high",
          category: "form",
          title: "Newsletter modal intercepts the cart",
          description:
            "A 10% off email capture opens over the cart on a 6-second timer and traps focus. On mobile widths it covers the order summary completely, and dismissal requires hitting a 24 px close target.",
          evidence: "Modal fires at 6.0 s · focus trap active · close target 24x24 px",
          selector: "#newsletter-modal",
        },
      ],
    },
  ],
};

const atelierNoir: ForensicAuditReport = {
  id: "atelier-noir",
  url: "https://atelier-noir.com/products/chunky-cashmere-crewneck",
  domain: "atelier-noir.com",
  status: "complete",
  blocked_reason: null,
  captured_at: "2026-08-07T16:48:03.000Z",
  run_duration_ms: 33940,
  steps: [
    { actor: "system", text: "Initializing forensic run 4a91 · budget 60s", delay_ms: 0, tone: "normal" },
    { actor: "browser", text: "Session acquired · chromium 128 · viewport 1280x1920", delay_ms: 700, tone: "normal" },
    { actor: "browser", text: "GET /products/chunky-cashmere-crewneck → 200 in 812ms", delay_ms: 850, tone: "normal" },
    { actor: "browser", text: "Network idle after 640ms · 31 requests", delay_ms: 700, tone: "success" },
    { actor: "vision", text: "Auditing product page: variant control has no selected state", delay_ms: 900, tone: "warn" },
    { actor: "browser", text: 'click button[name="add"] → blocked: size required', delay_ms: 850, tone: "warn" },
    { actor: "browser", text: 'Recovered · selected size "M" · re-dispatched click', delay_ms: 800, tone: "normal" },
    { actor: "browser", text: "No navigation · mini-cart drawer opened in 340ms", delay_ms: 800, tone: "normal" },
    { actor: "vision", text: "Stage 2 classified as mini-cart · auditing drawer", delay_ms: 900, tone: "normal" },
    { actor: "browser", text: "click .drawer__view-bag → navigation to /cart in 486ms", delay_ms: 850, tone: "normal" },
    { actor: "browser", text: "Console: clean · 0 errors", delay_ms: 600, tone: "success" },
    { actor: "vision", text: "Running CRO + WCAG pass over cart capture…", delay_ms: 950, tone: "normal" },
    { actor: "vision", text: "8 friction points across 3 stages · 1 contrast failure", delay_ms: 900, tone: "warn" },
    { actor: "system", text: "Report sealed · 3 stages · run complete", delay_ms: 600, tone: "success" },
  ],
  stages: [
    {
      id: "product",
      kind: "product",
      label: "Product page",
      url: "https://atelier-noir.com/products/chunky-cashmere-crewneck",
      transition_in: null,
      screenshot: {
        src: atelierProductShot,
        width: 1024,
        height: 1536,
        caption: "Product page as served, full-page capture at 1280 x 1920",
      },
      technical_metrics: {
        largest_contentful_paint_ms: 1420,
        cumulative_layout_shift: 0.018,
        total_blocking_time_ms: 70,
        dom_content_loaded_ms: 812,
        transfer_bytes: 1_240_064,
        request_count: 31,
        console_errors: [],
        slow_resources: [{ label: "editorial-crew-01.jpg (620 KB)", duration_ms: 540 }],
      },
      friction_points: [
        {
          id: 1,
          x_percentage: 72,
          y_percentage: 38.5,
          severity: "high",
          category: "form",
          title: "Size selector has no selected state",
          description:
            "XS through XL render as identical light grey labels with no border, fill, or aria-checked. Nothing tells the buyer a size is required until Add to Bag silently fails, and the agent had to recover before it could proceed.",
          evidence: "5 options · no [aria-checked] · agent click blocked once",
          selector: ".variant-picker",
        },
        {
          id: 2,
          x_percentage: 73,
          y_percentage: 45.4,
          severity: "medium",
          category: "trust",
          title: "Add to Bag reads as a secondary control",
          description:
            "The only conversion action on the page is a 1 px outlined rectangle, while the newsletter Subscribe block below it is solid black. The visual hierarchy points away from the sale.",
          evidence: "CTA: 1 px border, no fill · Subscribe: solid fill",
          selector: ".product-form__cta",
        },
        {
          id: 3,
          x_percentage: 69,
          y_percentage: 51.2,
          severity: "high",
          category: "accessibility",
          title: "Shipping and returns copy fails WCAG AA",
          description:
            "Complimentary shipping and Easy returns within 14 days render at #B4B4B4 on white — 1.9:1 against a 4.5:1 requirement. The two facts that most reduce purchase risk are effectively invisible.",
          evidence: "Measured contrast 1.9:1 · required 4.5:1",
          selector: ".product-meta__shipping",
        },
        {
          id: 4,
          x_percentage: 60,
          y_percentage: 28,
          severity: "low",
          category: "clarity",
          title: "No quantity control at all",
          description:
            "The page offers no way to buy two. A shopper who wants a second colourway or a gift pair has to complete the purchase and start over.",
          evidence: "No input[name='quantity'] in the product form",
          selector: ".product-form",
        },
      ],
    },
    {
      id: "mini-cart",
      kind: "mini-cart",
      label: "Mini-cart",
      url: "https://atelier-noir.com/products/chunky-cashmere-crewneck#cart-drawer",
      transition_in: { action: 'click button[name="add"] → drawer opened (no navigation)', duration_ms: 340 },
      screenshot: {
        src: atelierMiniCartShot,
        width: 1024,
        height: 1024,
        caption: "Mini-cart drawer over the product page, viewport capture at 1280 x 1280",
      },
      technical_metrics: {
        largest_contentful_paint_ms: 1284,
        cumulative_layout_shift: 0.006,
        total_blocking_time_ms: 30,
        dom_content_loaded_ms: 340,
        transfer_bytes: 96_256,
        request_count: 7,
        console_errors: [],
        slow_resources: [],
      },
      friction_points: [
        {
          id: 1,
          x_percentage: 83,
          y_percentage: 80.5,
          severity: "medium",
          category: "clarity",
          title: "View Bag and Checkout are stacked and equal-width",
          description:
            "The drawer's whole job is to send the buyer forward, yet the detour back to the bag sits directly above checkout at the same size. Two-thirds of drawer users take the top button.",
          evidence: "Both buttons 288 px wide · View Bag rendered first",
          selector: ".drawer__actions",
        },
        {
          id: 2,
          x_percentage: 83,
          y_percentage: 47,
          severity: "low",
          category: "clarity",
          title: "Free-shipping progress bar is unlabelled",
          description:
            "The bar shows $0 to $250 while the subtotal is already $480, so it reads as filled but the copy claims $20 remain. Two contradictory signals in a 60 px band.",
          evidence: "Bar scale 0–250 · subtotal 480 · copy says $20 away",
          selector: ".drawer__shipping-progress",
        },
      ],
    },
    {
      id: "cart",
      kind: "cart",
      label: "Cart",
      url: "https://atelier-noir.com/cart",
      transition_in: { action: "click .drawer__view-bag → navigate /cart", duration_ms: 486 },
      screenshot: {
        src: atelierCartShot,
        width: 1024,
        height: 1536,
        caption: "Cart page after View Bag, full-page capture at 1280 x 1920",
      },
      technical_metrics: {
        largest_contentful_paint_ms: 1284,
        cumulative_layout_shift: 0.011,
        total_blocking_time_ms: 60,
        dom_content_loaded_ms: 486,
        transfer_bytes: 742_400,
        request_count: 31,
        console_errors: [],
        slow_resources: [{ label: "cashmere-crew-black.jpg (240 KB)", duration_ms: 310 }],
      },
      friction_points: [
        {
          id: 1,
          x_percentage: 20,
          y_percentage: 56.5,
          severity: "high",
          category: "accessibility",
          title: "Shipping copy fails WCAG AA contrast",
          description:
            "Free shipping over $500 and Shipping to: United States render at #9A9A9A on #FFFFFF — a 2.8:1 ratio against a 4.5:1 requirement. The threshold that would drive a second item into the bag is the least legible text on the page.",
          evidence: "Measured contrast 2.8:1 · required 4.5:1",
          selector: ".shipping-note",
        },
        {
          id: 2,
          x_percentage: 75,
          y_percentage: 54.5,
          severity: "medium",
          category: "trust",
          title: "Checkout button reads as secondary",
          description:
            "The only conversion action is a thin outlined rectangle, visually subordinate to the solid black Subscribe button further down the page. Users scanning for the primary action land on the newsletter first.",
          evidence: "CTA: 1 px border, no fill · Subscribe: solid fill",
          selector: ".cart__checkout",
        },
        {
          id: 3,
          x_percentage: 88,
          y_percentage: 71,
          severity: "low",
          category: "clarity",
          title: "Email capture outranks the order",
          description:
            "The 10% off block sits immediately under the summary with the strongest button on the page, drawing intent away from checkout at the moment of decision.",
          evidence: "Subscribe block 168 px tall, directly below total",
          selector: ".newsletter-band",
        },
      ],
    },
  ],
};

const techBazaar: ForensicAuditReport = {
  id: "techbazaar",
  url: "https://techbazaar.example/c/wireless-headphones",
  domain: "techbazaar.example",
  status: "complete",
  blocked_reason: null,
  captured_at: "2026-08-06T11:02:47.000Z",
  run_duration_ms: 58610,
  steps: [
    { actor: "system", text: "Initializing forensic run c07d · budget 60s", delay_ms: 0, tone: "normal" },
    { actor: "browser", text: "Session acquired · chromium 128 · viewport 1280x1920", delay_ms: 700, tone: "normal" },
    { actor: "browser", text: "GET /c/wireless-headphones → 200 in 2860ms", delay_ms: 950, tone: "warn" },
    { actor: "vision", text: "Entry classified as category listing · auditing before descent", delay_ms: 900, tone: "normal" },
    { actor: "browser", text: "Dismissed interstitial: app-download overlay", delay_ms: 800, tone: "normal" },
    { actor: "browser", text: "click .product-card:nth-child(2) → /product/sony-wh-1000xm5 in 3418ms", delay_ms: 1000, tone: "warn" },
    { actor: "browser", text: "Network idle not reached in 8000ms · proceeding on DOM stable", delay_ms: 1050, tone: "warn" },
    { actor: "browser", text: "Accessibility tree extracted · 612 nodes · 27 button candidates", delay_ms: 850, tone: "normal" },
    { actor: "vision", text: "Candidate set ambiguous · 3 add-to-cart labels present", delay_ms: 900, tone: "warn" },
    { actor: "vision", text: "Selected #add-to-cart-primary · confidence 0.71", delay_ms: 850, tone: "normal" },
    { actor: "browser", text: "click() dispatched · navigation to /checkout/cart in 2960ms", delay_ms: 950, tone: "normal" },
    { actor: "browser", text: "Console: 5 errors captured during cart render", delay_ms: 700, tone: "error" },
    { actor: "browser", text: "Performance entries collected · LCP 4820ms · CLS 0.284", delay_ms: 750, tone: "error" },
    { actor: "vision", text: "12 friction points across 3 stages · 6 high severity", delay_ms: 950, tone: "error" },
    { actor: "system", text: "Report sealed · 3 stages · run complete", delay_ms: 600, tone: "success" },
  ],
  stages: [
    {
      id: "category",
      kind: "category",
      label: "Category",
      url: "https://techbazaar.example/c/wireless-headphones",
      transition_in: null,
      screenshot: {
        src: techCategoryShot,
        width: 1024,
        height: 1536,
        caption: "Category listing as served, full-page capture at 1280 x 1920",
      },
      technical_metrics: {
        largest_contentful_paint_ms: 3960,
        cumulative_layout_shift: 0.212,
        total_blocking_time_ms: 980,
        dom_content_loaded_ms: 2860,
        transfer_bytes: 6_214_656,
        request_count: 178,
        console_errors: [
          "Uncaught ReferenceError: dataLayer is not defined",
          "[Violation] 'setTimeout' handler took 340ms",
        ],
        slow_resources: [
          { label: "grid-sponsored-ads.js (480 KB)", duration_ms: 1980 },
          { label: "filter-facets.json", duration_ms: 1120 },
        ],
      },
      friction_points: [
        {
          id: 1,
          x_percentage: 50,
          y_percentage: 23,
          severity: "medium",
          category: "clarity",
          title: "Three offer banners precede the first product",
          description:
            "Bank offer, exchange offer, and no-cost EMI consume 130 px above the grid on a page the user arrived at to compare products.",
          evidence: "Banner row above first result card",
          selector: ".offer-strip",
        },
        {
          id: 2,
          x_percentage: 25,
          y_percentage: 44.1,
          severity: "high",
          category: "trust",
          title: "Sponsored results are indistinguishable from organic",
          description:
            "Three of the first four cards are labelled Sponsored in 10 px grey above the title, styled identically to the rest. The default Relevance sort therefore shows paid placement first without saying so.",
          evidence: "3 of 4 above-fold cards sponsored · label 10 px #878787",
          selector: ".product-card__sponsored",
        },
        {
          id: 3,
          x_percentage: 25,
          y_percentage: 54.2,
          severity: "medium",
          category: "form",
          title: "Card-level Add to cart skips variant choice",
          description:
            "Each card offers Add to cart directly from the grid, but colour and warranty are only selectable on the detail page. Grid adds silently commit the default variant.",
          evidence: "Grid CTA posts default SKU · no variant prompt",
          selector: ".product-card__cta",
        },
        {
          id: 4,
          x_percentage: 50,
          y_percentage: 96,
          severity: "high",
          category: "clarity",
          title: "App-download banner covers the last row",
          description:
            "A fixed 110 px promo bar overlays the bottom of the viewport for the entire session and hides one full row of results until dismissed via a 20 px close target.",
          evidence: "position: fixed · height 110 px · close target 20x20 px",
          selector: "#app-download-bar",
        },
      ],
    },
    {
      id: "product",
      kind: "product",
      label: "Product page",
      url: "https://techbazaar.example/product/sony-wh-1000xm5",
      transition_in: { action: "click .product-card:nth-child(2) → navigate /product", duration_ms: 3418 },
      screenshot: {
        src: techProductShot,
        width: 1024,
        height: 1536,
        caption: "Product detail page, full-page capture at 1280 x 1920",
      },
      technical_metrics: {
        largest_contentful_paint_ms: 4410,
        cumulative_layout_shift: 0.244,
        total_blocking_time_ms: 1120,
        dom_content_loaded_ms: 3418,
        transfer_bytes: 8_602_112,
        request_count: 231,
        console_errors: [
          "Uncaught ReferenceError: dataLayer is not defined",
          'Failed to load resource: 404 "/static/emi-widget.v3.css"',
          "Mixed Content: requested an insecure image 'http://cdn.techbazaar.example/badge.png'",
        ],
        slow_resources: [
          { label: "livechat-sdk.js (612 KB)", duration_ms: 2180 },
          { label: "exchange-offer-carousel.js", duration_ms: 1640 },
          { label: "gallery-zoom.bundle.js", duration_ms: 1180 },
        ],
      },
      friction_points: [
        {
          id: 1,
          x_percentage: 70,
          y_percentage: 39,
          severity: "medium",
          category: "clarity",
          title: "Four bank offers plus 18 more, before the price sinks in",
          description:
            "The offer block runs longer than the product description and every line ends in a T&C link. Working out the real price requires reading a legal document.",
          evidence: "4 visible offers · 'View 18 more offers'",
          selector: ".offers-list",
        },
        {
          id: 2,
          x_percentage: 63,
          y_percentage: 59.4,
          severity: "high",
          category: "form",
          title: "Delivery date is gated behind a pincode",
          description:
            "The page shows a pre-filled pincode with a Check button and a tooltip demanding entry. Until it is resolved, delivery, exchange value, and the final price are all unknown.",
          evidence: "Tooltip 'Enter delivery pincode' blocks exchange and delivery rows",
          selector: "#pincode-check",
        },
        {
          id: 3,
          x_percentage: 50,
          y_percentage: 73.5,
          severity: "high",
          category: "form",
          title: "Three warranty upsells sit above the buy button",
          description:
            "Extended-warranty checkboxes at ₹179, ₹299, and ₹399 are the last thing between the buyer and Add to Cart, adding a three-way decision to a purchase they already made.",
          evidence: "3 unchecked options · 168 px tall block directly above CTA",
          selector: "#warranty-upsell",
        },
        {
          id: 4,
          x_percentage: 68,
          y_percentage: 85,
          severity: "high",
          category: "clarity",
          title: "Add to Cart and Buy Now are equally loud",
          description:
            "Two saturated buttons of identical size sit side by side in orange and yellow. Neither is dominant, and Buy Now silently skips the cart the user may have been building.",
          evidence: "Both 236x56 px · adjacent · no visual hierarchy",
          selector: ".pdp-actions",
        },
        {
          id: 5,
          x_percentage: 84,
          y_percentage: 93.7,
          severity: "medium",
          category: "trust",
          title: "Chat widget opens unprompted over the CTA row",
          description:
            "The live chat panel expands on load at 1280 px width and overlaps the bottom-right of the action row, covering part of Buy Now until dismissed.",
          evidence: "Widget 320x220 px · z-index above CTA row",
          selector: "#livechat-root",
        },
      ],
    },
    {
      id: "cart",
      kind: "cart",
      label: "Cart",
      url: "https://techbazaar.example/checkout/cart",
      transition_in: { action: "click #add-to-cart-primary → navigate /checkout/cart", duration_ms: 2960 },
      screenshot: {
        src: techCartShot,
        width: 1024,
        height: 1536,
        caption: "Cart step of the 4-step checkout, full-page capture at 1280 x 1920",
      },
      technical_metrics: {
        largest_contentful_paint_ms: 4820,
        cumulative_layout_shift: 0.284,
        total_blocking_time_ms: 1240,
        dom_content_loaded_ms: 2960,
        transfer_bytes: 7_918_182,
        request_count: 214,
        console_errors: [
          "Uncaught ReferenceError: dataLayer is not defined",
          'Failed to load resource: 404 "/static/emi-widget.v3.css"',
          "Mixed Content: requested an insecure image 'http://cdn.techbazaar.example/badge.png'",
          "Uncaught (in promise) DOMException: play() failed because the user didn't interact",
          "[Violation] 'setTimeout' handler took 412ms",
        ],
        slow_resources: [
          { label: "livechat-sdk.js (612 KB)", duration_ms: 2180 },
          { label: "exchange-offer-carousel.js", duration_ms: 1640 },
          { label: "recommendations-v4.json", duration_ms: 1210 },
          { label: "payment-logos-sprite.png", duration_ms: 780 },
        ],
      },
      friction_points: [
        {
          id: 1,
          x_percentage: 50,
          y_percentage: 12,
          severity: "medium",
          category: "clarity",
          title: "Three promotional banners precede the cart",
          description:
            "Bank offer, exchange offer, and free delivery banners consume the first 210 px of the checkout step. The user has already decided to buy; the page is still selling.",
          evidence: "Banner stack 210 px above the cart heading",
          selector: ".offer-banners",
        },
        {
          id: 2,
          x_percentage: 50,
          y_percentage: 19.7,
          severity: "high",
          category: "clarity",
          title: "Step indicator numbering is broken",
          description:
            "The progress rail labels both Payment and Place Order as step 3. Users cannot tell how many steps remain, which is the single strongest predictor of checkout abandonment.",
          evidence: "Steps render 1, 2, 3, 3",
          selector: ".checkout-steps",
        },
        {
          id: 3,
          x_percentage: 34,
          y_percentage: 43.5,
          severity: "high",
          category: "form",
          title: "Warranty upsell repeats inside the cart",
          description:
            "The same three extended-warranty checkboxes reappear between the product row and the payment section, asking a decision worth up to ₹2,999 for the second time in one flow.",
          evidence: "3 unchecked options · 168 px tall block mid-flow",
          selector: "#warranty-upsell",
        },
        {
          id: 4,
          x_percentage: 41,
          y_percentage: 60,
          severity: "high",
          category: "form",
          title: "Payment selection before order confirmation",
          description:
            "The full payment method matrix — UPI, cards, net banking, EMI, wallets, COD — with a live QR code renders inside the cart step, before the user has reviewed the address. The QR expires on a timer they cannot see.",
          evidence: "Payment block 280 px tall, inside step 1 of 4",
          selector: ".payment-options",
        },
        {
          id: 5,
          x_percentage: 87,
          y_percentage: 75,
          severity: "medium",
          category: "trust",
          title: "Chat widget covers the Continue button",
          description:
            "The live chat panel opens unprompted at 1280 px width and overlaps the right rail, obscuring the Continue button until dismissed.",
          evidence: "Widget 320x420 px, z-index above CTA column",
          selector: "#livechat-root",
        },
      ],
    },
  ],
};

const blockedRun: ForensicAuditReport = {
  id: "northsupply-blocked",
  url: "https://northsupply.example/p/merino-base-layer",
  domain: "northsupply.example",
  status: "partial",
  blocked_reason:
    "Bot-protection interlock held the session for the full navigation budget. No product DOM was ever served, so neither the product page nor the cart could be audited.",
  captured_at: "2026-08-08T08:31:10.000Z",
  run_duration_ms: 60000,
  steps: [
    { actor: "system", text: "Initializing forensic run 21be · budget 60s", delay_ms: 0, tone: "normal" },
    { actor: "browser", text: "Session acquired · chromium 128 · viewport 1280x1920", delay_ms: 700, tone: "normal" },
    { actor: "browser", text: "GET /p/merino-base-layer → 403 in 640ms", delay_ms: 900, tone: "warn" },
    { actor: "browser", text: "Interlock detected: managed challenge · ray 7f9c2e1d", delay_ms: 850, tone: "warn" },
    { actor: "browser", text: "Retry 1/2 with residential egress → challenge persists", delay_ms: 1100, tone: "warn" },
    { actor: "browser", text: "Retry 2/2 after 6s backoff → challenge persists", delay_ms: 1100, tone: "error" },
    { actor: "system", text: "Navigation budget exhausted at 60000ms", delay_ms: 800, tone: "error" },
    { actor: "vision", text: "No product DOM available · skipping cart traversal", delay_ms: 700, tone: "warn" },
    { actor: "vision", text: "Auditing what was served instead", delay_ms: 900, tone: "normal" },
    { actor: "system", text: "Partial report sealed · 1 of 2 expected stages", delay_ms: 600, tone: "warn" },
  ],
  stages: [
    {
      id: "product",
      kind: "product",
      label: "Product page (blocked)",
      url: "https://northsupply.example/p/merino-base-layer",
      transition_in: null,
      screenshot: {
        src: blockedShot,
        width: 1024,
        height: 1024,
        caption: "Interlock page served in place of the product page",
      },
      technical_metrics: {
        largest_contentful_paint_ms: 780,
        cumulative_layout_shift: 0.004,
        total_blocking_time_ms: 20,
        dom_content_loaded_ms: 402,
        transfer_bytes: 48_128,
        request_count: 6,
        console_errors: [],
        slow_resources: [],
      },
      friction_points: [
        {
          id: 1,
          x_percentage: 50,
          y_percentage: 50,
          severity: "high",
          category: "trust",
          title: "Interlock served to a legitimate desktop session",
          description:
            "A standard Chromium session with a normal user agent was challenged and never released. Whatever the intent, real customers on VPNs, corporate networks, and privacy browsers hit exactly this wall and never see a product.",
          evidence: "403 on first request · challenge unresolved after 2 retries",
          selector: "#challenge-form",
        },
      ],
    },
  ],
};

export const fixtureReports: ForensicAuditReport[] = [
  wayfarer,
  techBazaar,
  atelierNoir,
  blockedRun,
];

export function getReportById(id: string): ForensicAuditReport | undefined {
  return fixtureReports.find((r) => r.id === id);
}
