/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRunIdRouteImport } from './routes/audit.$runId'
import { Route as AuditLiveRouteImport } from './routes/audit.live'
import { Route as ReportReportIdRouteImport } from './routes/report.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRunIdRoute = AuditRunIdRouteImport.update({
  id: '/audit/$runId',
  path: '/audit/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLiveRoute = AuditLiveRouteImport.update({
  id: '/audit/live',
  path: '/audit/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportReportIdRoute = ReportReportIdRouteImport.update({
  id: '/report/$reportId',
  path: '/report/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit/$runId': typeof AuditRunIdRoute
  '/audit/live': typeof AuditLiveRoute
  '/report/$reportId': typeof ReportReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit/$runId': typeof AuditRunIdRoute
  '/audit/live': typeof AuditLiveRoute
  '/report/$reportId': typeof ReportReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit/$runId': typeof AuditRunIdRoute
  '/audit/live': typeof AuditLiveRoute
  '/report/$reportId': typeof ReportReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audit/$runId' | '/audit/live' | '/report/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audit/$runId' | '/audit/live' | '/report/$reportId'
  id: '__root__' | '/' | '/audit/$runId' | '/audit/live' | '/report/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRunIdRoute: typeof AuditRunIdRoute
  AuditLiveRoute: typeof AuditLiveRoute
  ReportReportIdRoute: typeof ReportReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/$runId': {
      id: '/audit/$runId'
      path: '/audit/$runId'
      fullPath: '/audit/$runId'
      preLoaderRoute: typeof AuditRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/live': {
      id: '/audit/live'
      path: '/audit/live'
      fullPath: '/audit/live'
      preLoaderRoute: typeof AuditLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$reportId': {
      id: '/report/$reportId'
      path: '/report/$reportId'
      fullPath: '/report/$reportId'
      preLoaderRoute: typeof ReportReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRunIdRoute: AuditRunIdRoute,
  AuditLiveRoute: AuditLiveRoute,
  ReportReportIdRoute: ReportReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
