/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as ReportReportIdRouteImport } from './routes/report.$reportId'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAuditRunIdRouteImport } from './routes/_authenticated/app.audit.$runId'
import { Route as AuthenticatedAppAuditLiveRouteImport } from './routes/_authenticated/app.audit.live'
import { Route as AuthenticatedAppReportReportIdRouteImport } from './routes/_authenticated/app.report.$reportId'
import { Route as ApiPublicThumbIdRouteImport } from './routes/api/public/thumb.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportReportIdRoute = ReportReportIdRouteImport.update({
  id: '/report/$reportId',
  path: '/report/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAuditRunIdRoute =
  AuthenticatedAppAuditRunIdRouteImport.update({
    id: '/app/audit/$runId',
    path: '/app/audit/$runId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAuditLiveRoute =
  AuthenticatedAppAuditLiveRouteImport.update({
    id: '/app/audit/live',
    path: '/app/audit/live',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppReportReportIdRoute =
  AuthenticatedAppReportReportIdRouteImport.update({
    id: '/app/report/$reportId',
    path: '/app/report/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicThumbIdRoute = ApiPublicThumbIdRouteImport.update({
  id: '/api/public/thumb/$id',
  path: '/api/public/thumb/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/r/$token': typeof RTokenRoute
  '/report/$reportId': typeof ReportReportIdRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/audit/$runId': typeof AuthenticatedAppAuditRunIdRoute
  '/app/audit/live': typeof AuthenticatedAppAuditLiveRoute
  '/app/report/$reportId': typeof AuthenticatedAppReportReportIdRoute
  '/api/public/thumb/$id': typeof ApiPublicThumbIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/r/$token': typeof RTokenRoute
  '/report/$reportId': typeof ReportReportIdRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/audit/$runId': typeof AuthenticatedAppAuditRunIdRoute
  '/app/audit/live': typeof AuthenticatedAppAuditLiveRoute
  '/app/report/$reportId': typeof AuthenticatedAppReportReportIdRoute
  '/api/public/thumb/$id': typeof ApiPublicThumbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/r/$token': typeof RTokenRoute
  '/report/$reportId': typeof ReportReportIdRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/audit/$runId': typeof AuthenticatedAppAuditRunIdRoute
  '/_authenticated/app/audit/live': typeof AuthenticatedAppAuditLiveRoute
  '/_authenticated/app/report/$reportId': typeof AuthenticatedAppReportReportIdRoute
  '/api/public/thumb/$id': typeof ApiPublicThumbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/r/$token'
    | '/report/$reportId'
    | '/app/'
    | '/app/audit/$runId'
    | '/app/audit/live'
    | '/app/report/$reportId'
    | '/api/public/thumb/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/r/$token'
    | '/report/$reportId'
    | '/app'
    | '/app/audit/$runId'
    | '/app/audit/live'
    | '/app/report/$reportId'
    | '/api/public/thumb/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/r/$token'
    | '/report/$reportId'
    | '/_authenticated/app/'
    | '/_authenticated/app/audit/$runId'
    | '/_authenticated/app/audit/live'
    | '/_authenticated/app/report/$reportId'
    | '/api/public/thumb/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RTokenRoute: typeof RTokenRoute
  ReportReportIdRoute: typeof ReportReportIdRoute
  ApiPublicThumbIdRoute: typeof ApiPublicThumbIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$reportId': {
      id: '/report/$reportId'
      path: '/report/$reportId'
      fullPath: '/report/$reportId'
      preLoaderRoute: typeof ReportReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/audit/$runId': {
      id: '/_authenticated/app/audit/$runId'
      path: '/app/audit/$runId'
      fullPath: '/app/audit/$runId'
      preLoaderRoute: typeof AuthenticatedAppAuditRunIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/audit/live': {
      id: '/_authenticated/app/audit/live'
      path: '/app/audit/live'
      fullPath: '/app/audit/live'
      preLoaderRoute: typeof AuthenticatedAppAuditLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/report/$reportId': {
      id: '/_authenticated/app/report/$reportId'
      path: '/app/report/$reportId'
      fullPath: '/app/report/$reportId'
      preLoaderRoute: typeof AuthenticatedAppReportReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/thumb/$id': {
      id: '/api/public/thumb/$id'
      path: '/api/public/thumb/$id'
      fullPath: '/api/public/thumb/$id'
      preLoaderRoute: typeof ApiPublicThumbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAuditRunIdRoute: typeof AuthenticatedAppAuditRunIdRoute
  AuthenticatedAppAuditLiveRoute: typeof AuthenticatedAppAuditLiveRoute
  AuthenticatedAppReportReportIdRoute: typeof AuthenticatedAppReportReportIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAuditRunIdRoute: AuthenticatedAppAuditRunIdRoute,
  AuthenticatedAppAuditLiveRoute: AuthenticatedAppAuditLiveRoute,
  AuthenticatedAppReportReportIdRoute: AuthenticatedAppReportReportIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RTokenRoute: RTokenRoute,
  ReportReportIdRoute: ReportReportIdRoute,
  ApiPublicThumbIdRoute: ApiPublicThumbIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
